version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "6081:6081"
    environment:
      - GO_ENV=development
      - BACKEND_PORT=6081
      - DB_PATH=/data/upm-dev.db
    volumes:
      - ./backend/data:/data
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "6071:6071"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:6081
