version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "6081:6081"
    environment:
      - GO_ENV=development
      - BACKEND_PORT=6081
      - DB_PATH=/data/upm-dev.db
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - NGINX_CONFIG_PATH=/etc/nginx/sites-available
      - NGINX_RELOAD_CMD=nginx -s reload
    volumes:
      - ./backend/data:/data
      - ./backend:/app
      - ./nginx/sites-available:/etc/nginx/sites-available
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "6071:6071"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:6081