package services

import (
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"upm-backend/internal/models"
)

type CertificateService struct {
	CertPath string
}

func NewCertificateService(certPath string) *CertificateService {
	return &CertificateService{
		CertPath: certPath,
	}
}

// ValidateCertificate validates a certificate file
func (c *CertificateService) ValidateCertificate(certPath, keyPath string) (*models.Certificate, error) {
	// Read certificate file
	certData, err := os.ReadFile(certPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read certificate file: %w", err)
	}

	// Read private key file
	keyData, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read private key file: %w", err)
	}

	// Parse certificate
	cert, err := tls.X509KeyPair(certData, keyData)
	if err != nil {
		return nil, fmt.Errorf("failed to parse certificate: %w", err)
	}

	// Parse X.509 certificate
	x509Cert, err := x509.ParseCertificate(cert.Certificate[0])
	if err != nil {
		return nil, fmt.Errorf("failed to parse X.509 certificate: %w", err)
	}

	// Extract domain from certificate
	domain := x509Cert.Subject.CommonName
	if domain == "" && len(x509Cert.DNSNames) > 0 {
		domain = x509Cert.DNSNames[0]
	}

	// Check if certificate is valid
	isValid := time.Now().Before(x509Cert.NotAfter)

	return &models.Certificate{
		Domain:    domain,
		CertPath:  certPath,
		KeyPath:   keyPath,
		ExpiresAt: x509Cert.NotAfter,
		IsValid:   isValid,
	}, nil
}

// GenerateLetsEncryptCertificate generates a certificate using Let's Encrypt
// This is a placeholder implementation - in production, you'd use an ACME client
func (c *CertificateService) GenerateLetsEncryptCertificate(domain string) (*models.Certificate, error) {
	// TODO: Implement actual Let's Encrypt integration using an ACME client
	// For now, return a placeholder certificate structure
	
	certPath := filepath.Join(c.CertPath, domain+".crt")
	keyPath := filepath.Join(c.CertPath, domain+".key")
	
	// Create placeholder files (in production, these would be generated by ACME)
	if err := c.createPlaceholderCertificate(domain, certPath, keyPath); err != nil {
		return nil, fmt.Errorf("failed to create placeholder certificate: %w", err)
	}

	return &models.Certificate{
		Domain:    domain,
		CertPath:  certPath,
		KeyPath:   keyPath,
		ExpiresAt: time.Now().AddDate(0, 0, 90), // 90 days from now
		IsValid:   true,
	}, nil
}

// createPlaceholderCertificate creates placeholder certificate files
// This is for development/testing purposes only
func (c *CertificateService) createPlaceholderCertificate(domain, certPath, keyPath string) error {
	// Ensure certificate directory exists
	if err := os.MkdirAll(filepath.Dir(certPath), 0755); err != nil {
		return fmt.Errorf("failed to create certificate directory: %w", err)
	}

	// Create placeholder certificate file
	certContent := fmt.Sprintf(`-----BEGIN CERTIFICATE-----
PLACEHOLDER CERTIFICATE FOR %s
This is a placeholder certificate for development purposes.
In production, this would be a real Let's Encrypt certificate.
-----END CERTIFICATE-----`, domain)

	if err := os.WriteFile(certPath, []byte(certContent), 0644); err != nil {
		return fmt.Errorf("failed to write certificate file: %w", err)
	}

	// Create placeholder private key file
	keyContent := fmt.Sprintf(`-----BEGIN PRIVATE KEY-----
PLACEHOLDER PRIVATE KEY FOR %s
This is a placeholder private key for development purposes.
In production, this would be a real private key.
-----END PRIVATE KEY-----`, domain)

	if err := os.WriteFile(keyPath, []byte(keyContent), 0600); err != nil {
		return fmt.Errorf("failed to write private key file: %w", err)
	}

	return nil
}

// RenewCertificate renews a certificate using Let's Encrypt
func (c *CertificateService) RenewCertificate(cert *models.Certificate) (*models.Certificate, error) {
	// TODO: Implement actual Let's Encrypt renewal using an ACME client
	// For now, just update the expiration date
	
	cert.ExpiresAt = time.Now().AddDate(0, 0, 90) // 90 days from now
	cert.IsValid = true
	cert.UpdatedAt = time.Now()

	return cert, nil
}

// CheckCertificateExpiry checks if a certificate is expiring soon
func (c *CertificateService) CheckCertificateExpiry(cert *models.Certificate) (bool, int) {
	now := time.Now()
	daysUntilExpiry := int(cert.ExpiresAt.Sub(now).Hours() / 24)
	
	// Consider expiring if less than 30 days
	return daysUntilExpiry <= 30, daysUntilExpiry
}

// GetCertificateInfo extracts information from a certificate file
func (c *CertificateService) GetCertificateInfo(certPath string) (*CertificateInfo, error) {
	certData, err := os.ReadFile(certPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read certificate file: %w", err)
	}

	// Parse certificate
	block, _ := pem.Decode(certData)
	if block == nil {
		return nil, fmt.Errorf("failed to decode PEM block")
	}

	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse certificate: %w", err)
	}

	return &CertificateInfo{
		Subject:    cert.Subject.CommonName,
		Issuer:     cert.Issuer.CommonName,
		NotBefore:  cert.NotBefore,
		NotAfter:   cert.NotAfter,
		DNSNames:   cert.DNSNames,
		IsValid:    time.Now().After(cert.NotBefore) && time.Now().Before(cert.NotAfter),
	}, nil
}

// CertificateInfo contains information about a certificate
type CertificateInfo struct {
	Subject   string
	Issuer    string
	NotBefore time.Time
	NotAfter  time.Time
	DNSNames  []string
	IsValid   bool
}
